In [11]:
from pandas import DataFrame, read_csv
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib
import numpy as np
from numpy import random 
%matplotlib inline

In [7]:
nomes = ['Paulo', 'Fernanda', 'Julia', 'Joao', 'Diogo']

In [15]:
random.seed(500)
random_nomes = [nomes[random.randint(low=0,high=len(nomes))] for i in range(1000)]

random_nomes[:10]

['Julia',
 'Fernanda',
 'Fernanda',
 'Paulo',
 'Fernanda',
 'Fernanda',
 'Fernanda',
 'Julia',
 'Julia',
 'Julia']

In [16]:
births = [random.randint(low=0,high=1000) for i in range(1000)]
births[:10]

[968, 155, 77, 578, 973, 124, 155, 403, 199, 191]

In [18]:
bebes_dados = list(zip(random_nomes, births))
bebes_dados

[('Julia', 968),
 ('Fernanda', 155),
 ('Fernanda', 77),
 ('Paulo', 578),
 ('Fernanda', 973),
 ('Fernanda', 124),
 ('Fernanda', 155),
 ('Julia', 403),
 ('Julia', 199),
 ('Julia', 191),
 ('Joao', 769),
 ('Paulo', 88),
 ('Paulo', 43),
 ('Julia', 393),
 ('Julia', 164),
 ('Joao', 45),
 ('Diogo', 148),
 ('Julia', 609),
 ('Diogo', 134),
 ('Joao', 726),
 ('Joao', 106),
 ('Diogo', 355),
 ('Fernanda', 774),
 ('Joao', 214),
 ('Fernanda', 732),
 ('Julia', 362),
 ('Julia', 682),
 ('Joao', 141),
 ('Fernanda', 433),
 ('Paulo', 892),
 ('Joao', 328),
 ('Fernanda', 151),
 ('Fernanda', 737),
 ('Joao', 200),
 ('Paulo', 626),
 ('Diogo', 679),
 ('Fernanda', 812),
 ('Diogo', 481),
 ('Diogo', 723),
 ('Julia', 98),
 ('Fernanda', 76),
 ('Diogo', 911),
 ('Diogo', 948),
 ('Diogo', 698),
 ('Diogo', 539),
 ('Paulo', 806),
 ('Joao', 885),
 ('Fernanda', 785),
 ('Fernanda', 750),
 ('Paulo', 233),
 ('Joao', 442),
 ('Joao', 170),
 ('Fernanda', 363),
 ('Paulo', 913),
 ('Paulo', 186),
 ('Joao', 510),
 ('Joao', 998),
 ('Joao', 12),
 ('Diogo', 804),
 ('Paulo', 705),
 ('Diogo', 900),
 ('Diogo', 727),
 ('Fernanda', 643),
 ('Julia', 34),
 ('Joao', 580),
 ('Joao', 287),
 ('Paulo', 382),
 ('Joao', 5),
 ('Julia', 204),
 ('Paulo', 392),
 ('Joao', 982),
 ('Diogo', 809),
 ('Joao', 62),
 ('Joao', 220),
 ('Paulo', 458),
 ('Julia', 738),
 ('Paulo', 502),
 ('Fernanda', 352),
 ('Diogo', 956),
 ('Fernanda', 326),
 ('Paulo', 791),
 ('Diogo', 724),
 ('Paulo', 414),
 ('Joao', 51),
 ('Fernanda', 295),
 ('Fernanda', 463),
 ('Joao', 922),
 ('Paulo', 693),
 ('Paulo', 353),
 ('Joao', 378),
 ('Paulo', 836),
 ('Fernanda', 10),
 ('Diogo', 279),
 ('Joao', 778),
 ('Fernanda', 10),
 ('Diogo', 370),
 ('Fernanda', 739),
 ('Fernanda', 682),
 ('Julia', 469),
 ('Diogo', 324),
 ('Joao', 612),
 ('Julia', 721),
 ('Joao', 410),
 ('Paulo', 474),
 ('Julia', 294),
 ('Fernanda', 128),
 ('Fernanda', 622),
 ('Julia', 588),
 ('Julia', 708),
 ('Fernanda', 286),
 ('Joao', 740),
 ('Diogo', 112),
 ('Fernanda', 128),
 ('Paulo', 195),
 ('Diogo', 458),
 ('Fernanda', 828),
 ('Joao', 576),
 ('Joao', 726),
 ('Diogo', 744),
 ('Fernanda', 449),
 ('Diogo', 814),
 ('Fernanda', 678),
 ('Paulo', 327),
 ('Diogo', 837),
 ('Fernanda', 904),
 ('Fernanda', 592),
 ('Paulo', 923),
 ('Paulo', 245),
 ('Diogo', 476),
 ('Diogo', 120),
 ('Julia', 656),
 ('Joao', 511),
 ('Julia', 398),
 ('Julia', 716),
 ('Fernanda', 657),
 ('Julia', 358),
 ('Julia', 510),
 ('Joao', 129),
 ('Diogo', 944),
 ('Joao', 490),
 ('Joao', 811),
 ('Diogo', 734),
 ('Diogo', 371),
 ('Joao', 37),
 ('Fernanda', 900),
 ('Diogo', 723),
 ('Diogo', 274),
 ('Joao', 291),
 ('Fernanda', 309),
 ('Fernanda', 143),
 ('Diogo', 277),
 ('Diogo', 116),
 ('Diogo', 11),
 ('Paulo', 49),
 ('Fernanda', 809),
 ('Joao', 28),
 ('Diogo', 407),
 ('Julia', 937),
 ('Paulo', 781),
 ('Fernanda', 236),
 ('Joao', 925),
 ('Paulo', 423),
 ('Diogo', 927),
 ('Diogo', 925),
 ('Paulo', 648),
 ('Joao', 481),
 ('Fernanda', 160),
 ('Paulo', 375),
 ('Paulo', 494),
 ('Joao', 623),
 ('Julia', 221),
 ('Joao', 378),
 ('Diogo', 951),
 ('Fernanda', 556),
 ('Diogo', 185),
 ('Joao', 434),
 ('Paulo', 340),
 ('Julia', 474),
 ('Diogo', 189),
 ('Julia', 606),
 ('Julia', 606),
 ('Fernanda', 331),
 ('Fernanda', 666),
 ('Joao', 105),
 ('Diogo', 182),
 ('Julia', 137),
 ('Julia', 543),
 ('Joao', 860),
 ('Julia', 701),
 ('Diogo', 564),
 ('Julia', 903),
 ('Paulo', 471),
 ('Diogo', 350),
 ('Paulo', 797),
 ('Julia', 945),
 ('Diogo', 912),
 ('Julia', 992),
 ('Julia', 203),
 ('Diogo', 93),
 ('Julia', 18),
 ('Joao', 787),
 ('Paulo', 543),
 ('Julia', 599),
 ('Paulo', 616),
 ('Julia', 290),
 ('Diogo', 388),
 ('Julia', 541),
 ('Fernanda', 906),
 ('Julia', 239),
 ('Joao', 269),
 ('Paulo', 621),
 ('Fernanda', 607),
 ('Julia', 336),
 ('Paulo', 775),
 ('Diogo', 242),
 ('Julia', 962),
 ('Paulo', 51),
 ('Fernanda', 24),
 ('Diogo', 124),
 ('Paulo', 976),
 ('Julia', 973),
 ('Diogo', 988),
 ('Fernanda', 722),
 ('Paulo', 969),
 ('Joao', 785),
 ('Fernanda', 446),
 ('Fernanda', 480),
 ('Paulo', 616),
 ('Fernanda', 221),
 ('Paulo', 578),
 ('Joao', 143),
 ('Paulo', 74),
 ('Fernanda', 21),
 ('Paulo', 994),
 ('Julia', 178),
 ('Julia', 946),
 ('Julia', 622),
 ('Joao', 978),
 ('Joao', 982),
 ('Diogo', 651),
 ('Diogo', 729),
 ('Julia', 836),
 ('Paulo', 762),
 ('Joao', 860),
 ('Joao', 928),
 ('Fernanda', 363),
 ('Fernanda', 594),
 ('Diogo', 752),
 ('Julia', 328),
 ('Fernanda', 934),
 ('Joao', 636),
 ('Joao', 921),
 ('Diogo', 591),
 ('Fernanda', 583),
 ('Fernanda', 587),
 ('Joao', 30),
 ('Julia', 378),
 ('Joao', 562),
 ('Paulo', 814),
 ('Joao', 623),
 ('Diogo', 169),
 ('Julia', 959),
 ('Fernanda', 99),
 ('Diogo', 629),
 ('Joao', 223),
 ('Paulo', 353),
 ('Joao', 157),
 ('Paulo', 915),
 ('Julia', 351),
 ('Julia', 206),
 ('Paulo', 292),
 ('Paulo', 401),
 ('Diogo', 296),
 ('Joao', 693),
 ('Paulo', 556),
 ('Julia', 905),
 ('Julia', 931),
 ('Joao', 825),
 ('Paulo', 936),
 ('Fernanda', 366),
 ('Joao', 618),
 ('Paulo', 394),
 ('Julia', 901),
 ('Julia', 355),
 ('Julia', 204),
 ('Julia', 34),
 ('Paulo', 785),
 ('Joao', 551),
 ('Julia', 937),
 ('Fernanda', 210),
 ('Fernanda', 163),
 ('Fernanda', 175),
 ('Paulo', 82),
 ('Joao', 855),
 ('Fernanda', 29),
 ('Diogo', 70),
 ('Joao', 308),
 ('Julia', 745),
 ('Diogo', 628),
 ('Paulo', 271),
 ('Fernanda', 506),
 ('Fernanda', 599),
 ('Fernanda', 317),
 ('Fernanda', 934),
 ('Julia', 626),
 ('Julia', 706),
 ('Fernanda', 615),
 ('Diogo', 688),
 ('Joao', 794),
 ('Julia', 71),
 ('Joao', 569),
 ('Joao', 981),
 ('Julia', 567),
 ('Julia', 285),
 ('Diogo', 958),
 ('Diogo', 859),
 ('Diogo', 495),
 ('Joao', 119),
 ('Fernanda', 562),
 ('Diogo', 279),
 ('Fernanda', 424),
 ('Fernanda', 330),
 ('Julia', 595),
 ('Fernanda', 187),
 ('Paulo', 327),
 ('Julia', 186),
 ('Julia', 827),
 ('Fernanda', 708),
 ('Julia', 349),
 ('Fernanda', 39),
 ('Diogo', 114),
 ('Joao', 647),
 ('Joao', 858),
 ('Diogo', 645),
 ('Diogo', 491),
 ('Paulo', 447),
 ('Diogo', 43),
 ('Joao', 449),
 ('Julia', 843),
 ('Paulo', 416),
 ('Julia', 624),
 ('Fernanda', 101),
 ('Paulo', 710),
 ('Julia', 451),
 ('Fernanda', 725),
 ('Diogo', 814),
 ('Paulo', 88),
 ('Diogo', 250),
 ('Paulo', 853),
 ('Fernanda', 373),
 ('Paulo', 868),
 ('Fernanda', 419),
 ('Paulo', 244),
 ('Joao', 137),
 ('Joao', 169),
 ('Paulo', 24),
 ('Julia', 693),
 ('Julia', 910),
 ('Julia', 685),
 ('Joao', 319),
 ('Joao', 915),
 ('Joao', 645),
 ('Paulo', 305),
 ('Diogo', 495),
 ('Diogo', 35),
 ('Diogo', 26),
 ('Julia', 293),
 ('Diogo', 476),
 ('Julia', 676),
 ('Julia', 517),
 ('Paulo', 428),
 ('Diogo', 729),
 ('Diogo', 326),
 ('Julia', 18),
 ('Fernanda', 38),
 ('Paulo', 661),
 ('Fernanda', 474),
 ('Paulo', 697),
 ('Diogo', 718),
 ('Diogo', 96),
 ('Julia', 864),
 ('Fernanda', 217),
 ('Fernanda', 894),
 ('Paulo', 922),
 ('Paulo', 454),
 ('Diogo', 390),
 ('Fernanda', 609),
 ('Joao', 761),
 ('Julia', 490),
 ('Diogo', 480),
 ('Paulo', 278),
 ('Joao', 71),
 ('Fernanda', 369),
 ('Joao', 176),
 ('Paulo', 155),
 ('Julia', 58),
 ('Paulo', 286),
 ('Julia', 347),
 ('Julia', 876),
 ('Diogo', 532),
 ('Paulo', 659),
 ('Paulo', 779),
 ('Diogo', 460),
 ('Diogo', 543),
 ('Julia', 156),
 ('Diogo', 142),
 ('Paulo', 675),
 ('Paulo', 992),
 ('Julia', 678),
 ('Diogo', 10),
 ('Fernanda', 143),
 ('Joao', 311),
 ('Joao', 118),
 ('Diogo', 67),
 ('Julia', 321),
 ('Julia', 262),
 ('Paulo', 632),
 ('Diogo', 4),
 ('Julia', 22),
 ('Diogo', 551),
 ('Paulo', 181),
 ('Paulo', 664),
 ('Diogo', 239),
 ('Julia', 601),
 ('Joao', 495),
 ('Fernanda', 482),
 ('Paulo', 3),
 ('Julia', 363),
 ('Paulo', 355),
 ('Julia', 983),
 ('Joao', 281),
 ('Fernanda', 236),
 ('Diogo', 63),
 ('Paulo', 97),
 ('Paulo', 385),
 ('Joao', 276),
 ('Diogo', 425),
 ('Fernanda', 539),
 ('Fernanda', 818),
 ('Diogo', 46),
 ('Joao', 341),
 ('Paulo', 461),
 ('Diogo', 657),
 ('Paulo', 511),
 ('Julia', 459),
 ('Fernanda', 246),
 ('Diogo', 529),
 ('Fernanda', 685),
 ('Paulo', 933),
 ('Joao', 901),
 ('Diogo', 246),
 ('Paulo', 953),
 ('Julia', 324),
 ('Julia', 122),
 ('Fernanda', 320),
 ('Diogo', 500),
 ('Paulo', 652),
 ('Julia', 382),
 ('Julia', 819),
 ('Paulo', 967),
 ('Fernanda', 778),
 ('Paulo', 781),
 ('Fernanda', 991),
 ('Paulo', 694),
 ('Julia', 784),
 ('Fernanda', 632),
 ('Paulo', 329),
 ('Julia', 881),
 ('Fernanda', 887),
 ('Julia', 412),
 ('Julia', 870),
 ('Fernanda', 715),
 ('Joao', 971),
 ('Fernanda', 372),
 ('Fernanda', 241),
 ('Julia', 421),
 ('Julia', 363),
 ('Julia', 407),
 ('Joao', 50),
 ('Fernanda', 415),
 ('Joao', 349),
 ('Julia', 657),
 ('Fernanda', 496),
 ('Diogo', 817),
 ('Paulo', 330),
 ('Diogo', 393),
 ('Joao', 302),
 ('Diogo', 392),
 ('Fernanda', 851),
 ('Joao', 615),
 ('Joao', 72),
 ('Fernanda', 404),
 ('Paulo', 668),
 ('Julia', 91),
 ('Diogo', 405),
 ('Diogo', 805),
 ('Fernanda', 211),
 ('Paulo', 552),
 ('Fernanda', 973),
 ('Diogo', 467),
 ('Fernanda', 554),
 ('Paulo', 533),
 ('Fernanda', 866),
 ('Diogo', 233),
 ('Julia', 890),
 ('Diogo', 844),
 ('Paulo', 67),
 ('Paulo', 762),
 ('Joao', 610),
 ('Fernanda', 196),
 ('Julia', 433),
 ('Paulo', 254),
 ('Julia', 638),
 ('Paulo', 775),
 ('Diogo', 984),
 ('Diogo', 466),
 ('Joao', 306),
 ('Julia', 450),
 ('Diogo', 158),
 ('Joao', 378),
 ('Diogo', 345),
 ('Julia', 741),
 ('Fernanda', 440),
 ('Paulo', 724),
 ('Fernanda', 637),
 ('Diogo', 505),
 ('Fernanda', 922),
 ('Joao', 560),
 ('Fernanda', 540),
 ('Julia', 964),
 ('Diogo', 988),
 ('Paulo', 381),
 ('Joao', 483),
 ('Julia', 989),
 ('Diogo', 42),
 ('Fernanda', 952),
 ('Joao', 658),
 ('Diogo', 167),
 ('Paulo', 654),
 ('Diogo', 684),
 ('Diogo', 403),
 ('Diogo', 399),
 ('Diogo', 576),
 ('Paulo', 540),
 ('Diogo', 498),
 ('Julia', 661),
 ('Fernanda', 802),
 ('Fernanda', 364),
 ('Julia', 491),
 ('Diogo', 953),
 ('Diogo', 785),
 ('Joao', 558),
 ('Paulo', 210),
 ('Julia', 744),
 ('Joao', 50),
 ('Fernanda', 616),
 ('Paulo', 476),
 ('Fernanda', 276),
 ('Julia', 290),
 ('Julia', 778),
 ('Paulo', 921),
 ('Julia', 224),
 ('Paulo', 791),
 ('Fernanda', 393),
 ('Diogo', 721),
 ('Paulo', 274),
 ('Julia', 671),
 ('Joao', 520),
 ('Fernanda', 283),
 ('Diogo', 715),
 ('Julia', 521),
 ('Diogo', 729),
 ('Julia', 223),
 ('Julia', 141),
 ('Paulo', 670),
 ('Paulo', 20),
 ('Julia', 488),
 ('Fernanda', 958),
 ('Paulo', 348),
 ('Paulo', 883),
 ('Joao', 592),
 ('Joao', 341),
 ('Paulo', 753),
 ('Julia', 541),
 ('Fernanda', 463),
 ('Fernanda', 905),
 ('Julia', 93),
 ('Julia', 217),
 ('Julia', 147),
 ('Paulo', 317),
 ('Diogo', 369),
 ('Paulo', 468),
 ('Diogo', 99),
 ('Paulo', 506),
 ('Diogo', 92),
 ('Joao', 245),
 ('Fernanda', 658),
 ('Paulo', 47),
 ('Julia', 72),
 ('Joao', 610),
 ('Fernanda', 23),
 ('Joao', 449),
 ('Joao', 561),
 ('Julia', 500),
 ('Fernanda', 442),
 ('Fernanda', 547),
 ('Joao', 169),
 ('Fernanda', 913),
 ('Fernanda', 795),
 ('Diogo', 249),
 ('Julia', 484),
 ('Paulo', 480),
 ('Joao', 926),
 ('Paulo', 357),
 ('Julia', 270),
 ('Julia', 606),
 ('Paulo', 487),
 ('Julia', 201),
 ('Fernanda', 331),
 ('Diogo', 840),
 ('Joao', 196),
 ('Joao', 515),
 ('Fernanda', 677),
 ('Paulo', 860),
 ('Joao', 396),
 ('Julia', 647),
 ('Fernanda', 634),
 ('Joao', 677),
 ('Fernanda', 762),
 ('Paulo', 977),
 ('Fernanda', 36),
 ('Diogo', 84),
 ('Paulo', 52),
 ('Julia', 532),
 ('Diogo', 980),
 ('Julia', 226),
 ('Julia', 72),
 ('Diogo', 124),
 ('Diogo', 659),
 ('Diogo', 430),
 ('Joao', 749),
 ('Joao', 334),
 ('Fernanda', 850),
 ('Julia', 397),
 ('Paulo', 579),
 ('Fernanda', 725),
 ('Joao', 695),
 ('Julia', 369),
 ('Joao', 318),
 ('Diogo', 731),
 ('Paulo', 329),
 ('Paulo', 128),
 ('Paulo', 282),
 ('Fernanda', 613),
 ('Fernanda', 785),
 ('Paulo', 647),
 ('Paulo', 513),
 ('Joao', 215),
 ('Joao', 227),
 ('Diogo', 389),
 ('Diogo', 561),
 ('Paulo', 862),
 ('Paulo', 783),
 ('Julia', 863),
 ('Diogo', 330),
 ('Joao', 12),
 ('Julia', 160),
 ('Fernanda', 208),
 ('Fernanda', 117),
 ('Julia', 737),
 ('Paulo', 912),
 ('Joao', 538),
 ('Diogo', 696),
 ('Paulo', 214),
 ('Joao', 618),
 ('Diogo', 833),
 ('Paulo', 570),
 ('Paulo', 28),
 ('Julia', 279),
 ('Joao', 140),
 ('Diogo', 586),
 ('Paulo', 987),
 ('Diogo', 108),
 ('Fernanda', 317),
 ('Diogo', 455),
 ('Diogo', 256),
 ('Diogo', 817),
 ('Diogo', 59),
 ('Joao', 92),
 ('Joao', 257),
 ('Diogo', 582),
 ('Fernanda', 490),
 ('Paulo', 702),
 ('Paulo', 382),
 ('Joao', 257),
 ('Joao', 756),
 ('Fernanda', 927),
 ('Joao', 142),
 ('Fernanda', 177),
 ('Julia', 497),
 ('Paulo', 514),
 ('Joao', 166),
 ('Fernanda', 625),
 ('Julia', 19),
 ('Joao', 373),
 ('Fernanda', 471),
 ('Paulo', 506),
 ('Fernanda', 520),
 ('Joao', 781),
 ('Julia', 494),
 ('Diogo', 441),
 ('Paulo', 380),
 ('Julia', 723),
 ('Paulo', 428),
 ('Paulo', 172),
 ('Paulo', 586),
 ('Joao', 568),
 ('Diogo', 742),
 ('Diogo', 940),
 ('Fernanda', 677),
 ('Diogo', 926),
 ('Joao', 438),
 ('Paulo', 642),
 ('Paulo', 747),
 ('Julia', 266),
 ('Joao', 993),
 ('Fernanda', 726),
 ('Paulo', 650),
 ('Paulo', 530),
 ('Paulo', 910),
 ('Paulo', 246),
 ('Paulo', 316),
 ('Diogo', 175),
 ('Paulo', 429),
 ('Diogo', 490),
 ('Fernanda', 875),
 ('Diogo', 260),
 ('Joao', 576),
 ('Paulo', 696),
 ('Diogo', 148),
 ('Fernanda', 914),
 ('Joao', 506),
 ('Fernanda', 703),
 ('Paulo', 908),
 ('Diogo', 921),
 ('Paulo', 260),
 ('Julia', 61),
 ('Julia', 874),
 ('Joao', 159),
 ('Diogo', 504),
 ('Joao', 756),
 ('Fernanda', 964),
 ('Paulo', 355),
 ('Diogo', 326),
 ('Fernanda', 494),
 ('Fernanda', 448),
 ('Fernanda', 997),
 ('Paulo', 141),
 ('Diogo', 704),
 ('Fernanda', 39),
 ('Fernanda', 347),
 ('Julia', 346),
 ('Joao', 185),
 ('Paulo', 254),
 ('Joao', 73),
 ('Joao', 946),
 ('Fernanda', 955),
 ('Paulo', 751),
 ('Julia', 950),
 ('Paulo', 478),
 ('Diogo', 911),
 ('Joao', 989),
 ('Paulo', 642),
 ('Julia', 223),
 ('Diogo', 166),
 ('Fernanda', 166),
 ('Paulo', 699),
 ('Diogo', 548),
 ('Joao', 796),
 ('Paulo', 182),
 ('Julia', 871),
 ('Diogo', 643),
 ('Fernanda', 682),
 ('Fernanda', 276),
 ('Julia', 883),
 ('Paulo', 77),
 ('Joao', 2),
 ('Diogo', 604),
 ('Joao', 918),
 ('Julia', 517),
 ('Julia', 694),
 ('Diogo', 799),
 ('Paulo', 32),
 ('Paulo', 978),
 ('Paulo', 574),
 ('Paulo', 279),
 ('Diogo', 400),
 ('Fernanda', 688),
 ('Fernanda', 805),
 ('Diogo', 617),
 ('Diogo', 153),
 ('Diogo', 139),
 ('Diogo', 119),
 ('Joao', 44),
 ('Julia', 718),
 ('Paulo', 421),
 ('Joao', 350),
 ('Joao', 552),
 ('Fernanda', 297),
 ('Paulo', 328),
 ('Paulo', 904),
 ('Diogo', 186),
 ('Julia', 876),
 ('Fernanda', 367),
 ('Joao', 683),
 ('Julia', 11),
 ('Paulo', 886),
 ('Fernanda', 493),
 ('Julia', 730),
 ('Paulo', 412),
 ('Joao', 485),
 ('Diogo', 794),
 ('Diogo', 888),
 ('Julia', 487),
 ('Fernanda', 335),
 ('Diogo', 504),
 ('Paulo', 895),
 ('Fernanda', 629),
 ('Joao', 587),
 ('Julia', 874),
 ('Paulo', 983),
 ('Diogo', 820),
 ('Joao', 481),
 ('Joao', 136),
 ('Joao', 164),
 ('Fernanda', 67),
 ('Joao', 353),
 ('Joao', 242),
 ('Paulo', 647),
 ('Fernanda', 202),
 ('Paulo', 98),
 ('Julia', 846),
 ('Julia', 522),
 ('Julia', 188),
 ('Paulo', 53),
 ('Fernanda', 193),
 ('Diogo', 338),
 ('Paulo', 101),
 ('Julia', 795),
 ('Joao', 652),
 ('Joao', 321),
 ('Joao', 104),
 ('Julia', 961),
 ('Paulo', 860),
 ('Fernanda', 70),
 ('Paulo', 425),
 ('Paulo', 633),
 ('Fernanda', 883),
 ('Julia', 687),
 ('Julia', 348),
 ('Diogo', 452),
 ('Paulo', 758),
 ('Joao', 432),
 ('Fernanda', 458),
 ('Julia', 923),
 ('Julia', 129),
 ('Fernanda', 790),
 ('Julia', 215),
 ('Diogo', 784),
 ('Paulo', 738),
 ('Julia', 840),
 ('Paulo', 874),
 ('Joao', 991),
 ('Joao', 218),
 ('Joao', 819),
 ('Fernanda', 556),
 ('Joao', 987),
 ('Paulo', 916),
 ('Fernanda', 304),
 ('Joao', 200),
 ('Joao', 494),
 ('Diogo', 455),
 ('Julia', 637),
 ('Julia', 608),
 ('Julia', 939),
 ('Julia', 909),
 ('Fernanda', 142),
 ('Julia', 778),
 ('Joao', 194),
 ('Diogo', 3),
 ('Julia', 40),
 ('Diogo', 888),
 ('Fernanda', 403),
 ('Paulo', 430),
 ('Paulo', 114),
 ('Joao', 624),
 ('Julia', 148),
 ('Julia', 160),
 ('Paulo', 411),
 ('Paulo', 552),
 ('Diogo', 569),
 ('Julia', 311),
 ('Diogo', 978),
 ('Joao', 423),
 ('Joao', 790),
 ('Paulo', 712),
 ('Joao', 738),
 ('Joao', 403),
 ('Diogo', 686),
 ('Diogo', 542),
 ('Joao', 152),
 ('Joao', 721),
 ('Paulo', 96),
 ('Joao', 896),
 ('Diogo', 496),
 ('Fernanda', 644),
 ('Diogo', 121),
 ('Joao', 614),
 ('Joao', 357),
 ('Diogo', 252),
 ('Paulo', 429),
 ('Fernanda', 969),
 ('Fernanda', 1),
 ('Diogo', 354),
 ('Fernanda', 107),
 ('Fernanda', 615),
 ('Julia', 591),
 ('Diogo', 517),
 ('Julia', 671),
 ('Julia', 758),
 ('Diogo', 991),
 ('Joao', 565),
 ('Diogo', 113),
 ('Joao', 564),
 ('Diogo', 787),
 ('Diogo', 562),
 ('Joao', 210),
 ('Joao', 207),
 ('Fernanda', 689),
 ('Julia', 66),
 ('Joao', 894),
 ('Fernanda', 348),
 ('Fernanda', 219),
 ('Joao', 928),
 ('Diogo', 956),
 ('Julia', 227),
 ('Julia', 129),
 ('Diogo', 608),
 ('Julia', 475),
 ('Diogo', 973),
 ('Diogo', 931),
 ('Fernanda', 16),
 ('Julia', 137),
 ('Diogo', 271),
 ('Paulo', 201),
 ('Julia', 124),
 ('Fernanda', 821),
 ('Fernanda', 29),
 ('Julia', 656),
 ('Paulo', 959),
 ('Paulo', 311),
 ('Paulo', 834),
 ('Paulo', 407),
 ('Paulo', 879),
 ('Paulo', 341),
 ('Joao', 813),
 ('Diogo', 545),
 ('Julia', 505),
 ('Julia', 310),
 ('Joao', 222),
 ('Fernanda', 572),
 ('Fernanda', 639),
 ('Fernanda', 566),
 ('Diogo', 739),
 ('Paulo', 78),
 ('Joao', 150),
 ('Julia', 463),
 ('Paulo', 715),
 ('Joao', 118),
 ('Diogo', 122),
 ('Fernanda', 276),
 ('Joao', 54),
 ('Joao', 32),
 ('Diogo', 931),
 ('Julia', 38),
 ('Diogo', 353),
 ('Diogo', 610),
 ('Fernanda', 954),
 ('Joao', 38),
 ('Diogo', 161),
 ('Fernanda', 691),
 ('Joao', 865),
 ('Paulo', 326),
 ('Diogo', 677),
 ('Fernanda', 706),
 ('Joao', 151),
 ('Fernanda', 511),
 ('Joao', 756),
 ('Fernanda', 294),
 ('Joao', 152)]

In [26]:
df1 = pd.DataFrame(data = bebes_dados, columns = ['Nomes', 'Nascimentos'])
df1[:10]

      Nomes  Nascimentos
0     Julia          968
1  Fernanda          155
2  Fernanda           77
3     Paulo          578
4  Fernanda          973
5  Fernanda          124
6  Fernanda          155
7     Julia          403
8     Julia          199
9     Julia          191

In [21]:
df.to_csv('nasci1880.txt', index = False, header = False)

In [34]:
location = r'C:\Users\Paulo\programacao\jupyter-notebooks\Pandas_tutorial\nasci1880.txt'
df2 = pd.read_csv(location, header = None)

In [38]:
df2.head()

          0    1
0     Julia  968
1  Fernanda  155
2  Fernanda   77
3     Paulo  578
4  Fernanda  973

In [39]:
df2.tail()

            0    1
995      Joao  151
996  Fernanda  511
997      Joao  756
998  Fernanda  294
999      Joao  152

In [42]:
df2 = read_csv(location, names = ['Nomes', 'Nascimentos'])
df2

        Nomes  Nascimentos
0       Julia          968
1    Fernanda          155
2    Fernanda           77
3       Paulo          578
4    Fernanda          973
5    Fernanda          124
6    Fernanda          155
7       Julia          403
8       Julia          199
9       Julia          191
10       Joao          769
11      Paulo           88
12      Paulo           43
13      Julia          393
14      Julia          164
15       Joao           45
16      Diogo          148
17      Julia          609
18      Diogo          134
19       Joao          726
20       Joao          106
21      Diogo          355
22   Fernanda          774
23       Joao          214
24   Fernanda          732
25      Julia          362
26      Julia          682
27       Joao          141
28   Fernanda          433
29      Paulo          892
..        ...          ...
970  Fernanda          572
971  Fernanda          639
972  Fernanda          566
973     Diogo          739
974     Paulo           78
975      Joao          150
976     Julia          463
977     Paulo          715
978      Joao          118
979     Diogo          122
980  Fernanda          276
981      Joao           54
982      Joao           32
983     Diogo          931
984     Julia           38
985     Diogo          353
986     Diogo          610
987  Fernanda          954
988      Joao           38
989     Diogo          161
990  Fernanda          691
991      Joao          865
992     Paulo          326
993     Diogo          677
994  Fernanda          706
995      Joao          151
996  Fernanda          511
997      Joao          756
998  Fernanda          294
999      Joao          152

[1000 rows x 2 columns]

In [43]:
df2['Nomes'].unique()

array(['Julia', 'Fernanda', 'Paulo', 'Joao', 'Diogo'], dtype=object)

In [44]:
for n in df2['Nomes'].unique():
    print(n)

Julia
Fernanda
Paulo
Joao
Diogo